### ISSUE TITLE
SBER_SAVING_2303 не работает если "Пополнение" или "Списание" содержат тысячи

### ISSUE THREAD

**Issue by Ev2geny** [Ev2geny/Sberbank2Excel#34]

**Comment by lensovet** [comment]
Добрый день, счета Пенсионный плюс и Активный возраст страдают от этой же проблемы?

```
Конвертируем файл /Users/paulb/Desktop/2023 Выписка по вкладу АВ.pdf
Произошла ошибка при конвертации файла "file" <class 'exceptions.InputFileStructureError'>
Traceback (most recent call last):
  File "/Users/paulb/Desktop/Sberbank2Excel/core/sberbankPDF2ExcelGUI.py", line 61, in btn_convertFiles_clicked
    sberbankPDF2Excel(file,
  File "/Users/paulb/Desktop/Sberbank2Excel/core/sberbankPDF2Excel.py", line 66, in sberbankPDF2Excel
    created_file_name = sberbankPDFtext2Excel(tmp_txt_file_name,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulb/Desktop/Sberbank2Excel/core/sberbankPDFtext2Excel.py", line 78, in sberbankPDFtext2Excel
    extractor_type = determine_extractor_auto(file_text)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulb/Desktop/Sberbank2Excel/core/extractors_generic.py", line 26, in determine_extractor_auto
    raise exceptions.InputFileStructureError("Неизвecтный формат выписки, ни один из экстракторов не подходят")
exceptions.InputFileStructureError: Неизвecтный формат выписки, ни один из экстракторов не подходят

Пропускаем конвертацию этого файла
!!!!!!! 1 файл(а) из 1 не были сконвертированы
```

Если нужен файл для тестирования, могу предоставить.

**Comment by Ev2geny** [comment]
> Добрый день, счета Пенсионный плюс и Активный возраст страдают от этой же проблемы?
> 
> Если нужен файл для тестирования, могу предоставить.

Здравствуйте, нет. такие счета просто не поддерживаются. Я создал отдельную issue для этого функционала https://github.com/Ev2geny/Sberbank2Excel/issues/35

Если вышлите файлы для тестирования, то постараюсь их добавить.  Вот [тут написано](https://github.com/Ev2geny/Sberbank2Excel?tab=readme-ov-file#section-8) какие есть варианты для пересылки

**Comment by Ev2geny** [comment]
Исправлено в [релизе 4.6.0](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v.4.6.0)
