### ISSUE TITLE
Формат типа SBER_DEBIT_2212 перестал работать случае странного знака валюты во второй строке трансакции

### ISSUE THREAD

**Issue by Ev2geny** [Ev2geny/Sberbank2Excel#39]
Сбер опять поменял формат и теперь на выписках типа  [SBER_DEBIT_2212 ](https://github.com/Ev2geny/Sberbank2Excel/blob/master/misc/format_examples/SBER_DEBIT_2212.png)во второй строке трансакции иногда появляется странный одинокий знак валюты.

![image](https://github.com/Ev2geny/Sberbank2Excel/assets/59611075/6b01b8d3-2743-458e-b3c8-1ae85381dfc0)

Sberbank2Excel такого не ожидает и в этих случаях выдаётся ошибка типа 

`Ожидалась струтура типа '6,79 €', получено: ₽`

```
Формат файла определён как SBER_DEBIT_2212
Error while processing entry
--------------------
31.03.2024      11:43   Неизвестная категория(-)        299,00
31.03.2024      076220  YM*YANDEX.PLUS Gorod Moskva RUS. Операция по карте ****XXXX     ₽

--------------------
Произошла ошибка при конвертации файла "file" <class 'exceptions.InputFileStructureError'>
Traceback (most recent call last):
  File "sberbankPDF2ExcelGUI.py", line 61, in btn_convertFiles_clicked
  File "sberbankPDF2Excel.py", line 66, in sberbankPDF2Excel
  File "sberbankPDFtext2Excel.py", line 98, in sberbankPDFtext2Excel
  File "extractor.py", line 105, in get_entries
  File "extractor.py", line 97, in get_entries
  File "extractor_SBER_DEBIT_2212.py", line 229, in decompose_entry_to_dict
exceptions.InputFileStructureError: Ошибка в обработке текста. Ожидалась струтура типа '6,79 €', получено: ₽

```

**Comment by Ev2geny** [comment]
Исправлено в релизе [4.6.1](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v4.6.1)
